!inherit
_BASE_: !include _base_.yaml
DATA:
  DIR:
      - ../Datasets/FastMRT Dataset V5.0/exvivo
  ACCELERATION: 2
MODEL:
  BASE_CHANNELS: 32          # Variable Param 07
  RES_BLOCK_NUM: 5            # Variable Param 08
  RES_CONV_KSIZE: 3           # Variable Param 09
  RES_CONV_NUM: 5             # Variable Param 10
  DROP_PROB: 0.1              # Variable Param 11
  LEAKYRELU_SLOPE: 0.1        # Variable Param 12
  LR: 5e-4                    # Variable Param 14
  LR_STEP_SIZE: 40            # Variable Param 15
  LR_GAMMA: 0.1               # Variable Param 16
  WEIGHT_DECAY: 0          # Variable Param 17
  LOSS_TYPE: l1
LOG:
  NAME: exp0617-3|casnet|test|exvivo|2X  # Baseline
AUGS:
  ENABLED: false
  CA_RATE: 0.3
KD:
  ENABLED: false
  TEA_DIR: ''
TEST:
  CKPT_DIR: /home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/CASNET/2lc4c08j/checkpoints/epoch=199-step=32400.ckpt

