!inherit
_BASE_: !include _base_.yaml
DATA:
  FORMAT: 'CF'
MODEL:
  IN_CHANNELS: 1              # Fixed Param
  OUT_CHANNELS: 1             # Fixed Param
  BASE_CHANNELS: 16           # Variable Param 07 recommend 32
  LEVEL_NUM: 4                # Variable Param 08 recommend 4
  DROP_PROB: 0.0              # Variable Param 09 毫无影响
  LEAKYRELU_SLOPE: 0.1        # Variable Param 10 recommend 0.1
  LAST_LAYER_WITH_ACT: False  # Variable Param 11 几乎无影响
  LR: 5e-4                    # Variable Param 12 recommend 1e-3
  LR_STEP_SIZE: 40            # Variable Param 13
  LR_GAMMA: 0.1               # Variable Param 14
  WEIGHT_DECAY: 0          # Variable Param 15 recommend 1e-4
  LOSS_TYPE: 'decoupled'
LOG:
  NAME: "exp0516-4|exvivo_sa|ca_rate=False|w/o_kd|loss=l1"  # Baseline
AUGS:
  ENABLED: False
  CA_RATE: 0.3
KD:
  ENABLED: false
  TEA_DIR: "/home/sxu/SJTU/FastMRT/fastMRT/Codes/logs/AUGS/30ycyzjc/checkpoints/epoch=199-step=101400.ckpt"




