!inherit
_BASE_: !include _base_.yaml
DATA:
  FORMAT: CF
  DIR:
      - ../Datasets/FastMRT Dataset V5.0/phantom
  ACCELERATION: 4
MODEL:
  IN_CHANNELS: 1              # Fixed Param
  OUT_CHANNELS: 1             # Fixed Param
  BASE_CHANNELS: 16           # Variable Param 07 recommend 32
  LEVEL_NUM: 4                # Variable Param 08 recommend 4
  DROP_PROB: 0.0              # Variable Param 09 毫无影响
  LEAKYRELU_SLOPE: 0.1        # Variable Param 10 recommend 0.1
  LR: 5e-4                    # Variable Param 12 recommend 1e-3
  WEIGHT_DECAY: 1e-4          # Variable Param 15 recommend 1e-4
  LOSS_TYPE: l1
LOG:
  NAME: exp0903-5|cunet|train-test|phantom|4X_wd1e-4  # Baseline
AUGS:
  ENABLED: false
  CA_RATE: 0.3
KD:
  ENABLED: false
  TEA_DIR: /home/sxu/SJTU/FastMRT/fastMRT/Codes/logs/AUGS/30ycyzjc/checkpoints/epoch=199-step=101400.ckpt
TEST:
  CKPT_DIR: /home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/CUNET/20mdd7vc/checkpoints/epoch=199-step=32400.ckpt




