DATA_DIR: '../Datasets/FastMRT Dataset V3.1'
PT_DATA_DIR: '../ImageNet/ILSVRC/Data/CLS-LOC/'
LOG_DIR: './logs/'
PRF_CONFIG_DIR: './configs/prf.yaml'
RUNET_CONFIG_DIR: './configs/runet.yaml'
RESUNET_CONFIG_DIR: './configs/resunet.yaml'
SWTNET_CONFIG_DIR: './configs/swtnet.yaml'
CASNET_CONFIG_DIR: './configs/casnet.yaml'
RFTNET_CONFIG_DIR: './configs/rftnet.yaml'
KDNET_CONFIG_DIR: './configs/kdnet.yaml'