DATA_DIR: '../Datasets/DatasetsV3.0'
PT_DATA_DIR: '../ImageNet/ILSVRC/Data/CLS-LOC/'
LOG_DIR: './logs/'
PRF_CONFIG_DIR: './configs/prf.yaml'
RUNET_CONFIG_DIR: './configs/runet.yaml'
CUNET_CONFIG_DIR: './configs/cunet.yaml'
CASNET_CONFIG_DIR: './configs/casnet.yaml'
RFTNET_CONFIG_DIR: './configs/rftnet.yaml'
KDNET_CONFIG_DIR: './configs/kdnet.yaml'
