# r-unet超参数配置文件

DATA:
  FORMAT: 'RF'       
  BATCH_SIZE: 8               
  SAMPLING_MODE: 'EQUISPACED' 
  ACCELERATION: 4             
  CENTER_FRACTION: 0.15       
MODEL:
  IN_CHANNELS: 2              
  OUT_CHANNELS: 2             
  BASE_CHANNELS_STU: 32           
  BASE_CHANNELS_TEA: 128
  LEVEL_NUM: 4                
  DROP_PROB: 0.0              
  LEAKYRELU_SLOPE: 0.1        
  LR: 5e-4                    
  WEIGHT_DECAY: 1e-4          
  LOSS_TYPE: 'l1'
  MAX_EPOCHS: 200             
  TEA_DIR: "/home/sxu/SJTU/FastMRT/fastMRT/Codes/logs/AUGS/30ycyzjc/checkpoints/epoch=199-step=101400.ckpt"
LOG:
  NAME: "exp0322-0|l1-loss_union=True|bc=32"  
  IMAGES_FRAME_IDX: 5     
  IMAGES_FREQ: 50         
  TMAP_PATCH_RATE: 4      
  TMAP_HEATED_THRESH: 43  
AUGS:
  AP_SHUFFLE: False
  UNION: True
  OBJS: []
  AP_LOGIC: "and"
  LIST: ["crop", "rotate", "blur", "flip"]
  COMPOSE_NUM: 1
