!inherit
_BASE_: !include _base_.yaml
DATA:
  DIR:
      - ../Datasets/FastMRT Dataset V5.0/exvivo
  ACCELERATION: 2
MODEL:
  BASE_CHANNELS: 32           # Variable Param 07 recommend 32
  CH_MULT: 
    - 1
    - 2
    - 2
    - 2
  ATTN: 
    - 3
  NUM_RES_BLOCKS: 2
  DROP_PROB: 0.1              # Variable Param 09 毫无影响
  LR: 5e-4                    # Variable Param 12 recommend 1e-3
  WEIGHT_DECAY: 0          # Variable Param 15 recommend 1e-4
  LOSS_TYPE: decoupled
LOG:
  NAME: exp0831-0|resunet+mim-kd-da|train-test|phantom|4X_wo-pretrain  # Baseline
AUGS:
  ENABLED: true
  CA_RATE: 0.3
KD:
  ENABLED: true
  TEA_DIR: /home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/RESUNET/1kcimc67/checkpoints/epoch=199-step=160400.ckpt
TEST:
  CKPT_DIR: /home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/RESUNET/1dbrzi40/checkpoints/epoch=199-step=160400.ckpt