# r-unet超参数配置文件

DATA:
  DATA_FORMAT: 'RF'           # Fixed Param
  BATCH_SIZE: 16               # Variable Param 01
  SAMPLING_MODE: 'EQUISPACED'     # Variable Param 02
  ACCELERATION: 2             # Variable Param 03
  CENTER_FRACTION: 0.2        # Variable Param 04
  RESIZE_SIZE: (256, 256)     # Variable Param 05
  RESIZE_MODE: 'on_kspace'    # Variable Param 06
MODEL:
  IN_CHANNELS: [2, 2, 2]              # Fixed Param
  OUT_CHANNELS: [2, 2, 2]             # Fixed Param
  BASE_CHANNELS: [32, 32, 24]            # Variable Param 07
  LEVEL_NUM: [4, 4, 3]                # Variable Param 08
  DROP_PROB: [0.0, 0.0, 0.0]            # Variable Param 09
  LEAKYRELU_SLOPE: [0.1, 0.1, 0.1]        # Variable Param 10
  LAST_LAYER_WITH_ACT: False  # Variable Param 11
  LR: 1e-4                    # Variable Param 12
  LR_STEP_SIZE: 1000            # Variable Param 13
  LR_GAMMA: 0.2               # Variable Param 14
  WEIGHT_DECAY: 1e-4          # Variable Param 15
  MAX_EPOCHS: 1000             # Independent Param
LOG:
  LOG_NAME: 'rftnet_test3_acc2'  # Independent Param
  LOG_IMAGES_FRAME_IDX: 5     # Independent Param
  LOG_IMAGES_FREQ: 50         # Independent Param
  TMAP_PATCH_RATE: 4          # Independent Param
  TMAP_MAX_TEMP_THRESH: 45    # Independent Param
  TMAP_ABLATION_THRESH: 43    # Independent Param




