!inherit
_BASE_: !include _base_.yaml
DATA:
  DIR:
      - ../Datasets/FastMRT Dataset V5.0/phantom
  ACCELERATION: 4
MODEL:
  BASE_CHANNELS: 32
  LEVEL_NUM: 4
  DROP_PROB: 0.0
  LEAKYRELU_SLOPE: 0.1
  LR: 5e-4
  WEIGHT_DECAY: 1e-4
  LOSS_TYPE: decoupled
LOG:
  NAME: exp0903-3|runet|train-test|phantom|4X_bc64  # Baseline
AUGS:
  ENABLED: false
  CA_RATE: 0.3
KD:
  ENABLED: false
  TEA_DIR: /home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/RUNET/9pqv6r9c/checkpoints/epoch=199-step=160400.ckpt
TEST:
  CKPT_DIR: /home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/RUNET/fe8kqif1/checkpoints/epoch=199-step=160400.ckpt