!inherit
_BASE_: !include _base_.yaml
MODEL:
  BASE_CHANNELS: 32
  LEVEL_NUM: 4
  DROP_PROB: 0.0
  LEAKYRELU_SLOPE: 0.1
  LR: 5e-4
  WEIGHT_DECAY: 1e-4
  LOSS_TYPE: 'l1'
LOG:
  NAME: "exp0518-3|phantom_os|ca_rate=False|w/_kd_gamma1.0|loss=l1"  # Baseline
AUGS:
  ENABLED: false
  CA_RATE: 0.3
KD:
  ENABLED: true
  TEA_DIR: "/home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/RUNET/1aa1ldav/checkpoints/epoch=199-step=299400.ckpt"




