!inherit
_BASE_: !include _base_.yaml
DATA:
  DIR:
      - ../Datasets/FastMRT Dataset V5.0/exvivo
  ACCELERATION: 2
MODEL:
  UPSCALE: 1
  IN_CHANNELS: 2
  IMG_SIZE: 
    - 96
    - 96
  PATCH_SIZE: 1
  WINDOW_SIZE: 8
  IMG_RANGE: 1.0
  DEPTHS: 
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
  EMBED_DIM: 180
  NUM_HEADS: 
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
  MLP_RATIO: 2.0
  UPSAMPLER: ''
  RESI_CONNECTION: 1conv
  LR: 2e-4                    # Variable Param 12 recommend 1e-3
  WEIGHT_DECAY: 0          # Variable Param 15 recommend 1e-4
  LOSS_TYPE: l1
LOG:
  NAME: exp0617-5|swtnet|test|exvivo|2X
AUGS:
  ENABLED: false
  CA_RATE: 0.3
KD:
  ENABLED: false
  TEA_DIR: ''
TEST:
  CKPT_DIR: /home/sxu/SJTU/FastMRT/fastMRT/FastMRT/logs/SWTNET/wegjpwch/checkpoints/epoch=199-step=32400.ckpt





